### ISSUE TITLE
Please Release Version: 10.4.1

### ISSUE THREAD

**Issue by xiaowang03** [webjars/mathjs#6]
https://github.com/josdejong/mathjs/tags

**Comment by xiaowang03** [comment]
Hi @jamesward,
Thank you for preparing the 10.4.1 release.
Unfortunately, it does not work: The files math.js and math.min.js are all empty.
Example of math.js:
`// TODO: deprecated since v8, remove this deprecation warning in v9
throw new Error('The non-minified file "mathjs/dist/math.js" has removed since mathjs@8.0.0. ' +
  'Please use the minified bundle "mathjs/lib/browser/math.js" instead.')`

It means that you need to take:
mathjs/lib/browser/math.js
mathjs/lib/browser/math.js.map

Thank you!

**Comment by jamesward** [comment]
Whoops. I'm releasing `10.4.1-1` now with the right files.
